$('.owl-carousel').owlCarousel({
    loop:false,
    margin:4,
    nav:false,
    responsive:{
        0:{
            items:2
        },
        600:{
            items:3
        },
        1000:{
            items:5
        },
        1200:{
            items:7
        }
    }
})